export FiltersDropdownTemplate from './components/filterPopover/search/filters/filtersDropdownTemplate.html';
export FilterMenuTemplate from './components/filterPopover/filterMenu/filterMenuTemplate.html';
export FollowerItemTemplate from './components/followerList/followerItem/followerItemTemplate.html';
export FollowerListTemplate from './components/followerList/followerListTemplate.html';
export InfoTemplate from './components/info/infoTemplate.html';
export PostViewTemplate from './components/postView/postViewTemplate.html';
export PopoverTemplate from './components/popover/popoverTemplate.html';
export SearchResultsTemplate from './components/searchResults/searchResultsTemplate.html';
export SearchTemplate from './components/filterPopover/search/searchTemplate.html';
export ToggleTemplate from './components/popover/toggle/toggle.html';
export TestTemplate from './components/tests/testTemplate.html'
